-- TASK_SYSTEM = 
-- { 
-- _maxTasksForPlayer = 3,
-- _reportTaskMode = "normal",


-- [1] = { name = "Spider",
        -- monsterList = { "Spider", "Poison Spider", "Tarantule" },
		-- minLevel = 1, 
		-- maxLevel = 50,
		-- kills = 70, 
		-- ["Rewards"] = { 
		                -- { type = "experience", value = 50000 },
						-- -- { type = "tibia coin", value = 10 },
						-- -- { type = "tournament coin", value = 30 },
						-- { type = "item", item_id = 2160, count = 2 },
						-- { type = "item", item_id = 37606, count = 7 },
					  -- }
	   -- },
-- -- [2] = { name = "Troll",
        -- -- monsterList = { "Troll", "Troll Champion" },
		-- -- minLevel = 1, 
		-- -- maxLevel = 50,
		-- -- kills = 70, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 30000 },
						-- -- { type = "item", item_id = 37606, count = 7 },
						-- -- { type = "item", item_id = 2160, count = 2 },
					  -- -- }
	   -- -- },
 -- -- [3] = { name = "Skeleton",
        -- -- monsterList = { "Skeleton", "Skeleton Warrior" },
		-- -- minLevel = 1, 
		-- -- maxLevel = 50,
		-- -- kills = 80, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 40000 },
						-- -- { type = "item", item_id = 37606, count = 7 },
						-- -- { type = "item", item_id = 2160, count = 10 },
					  -- -- }
	   -- -- },
-- -- [4] = { name = "Mummy",
        -- -- monsterList = { "Mummy", "Crypt Shambler", "Tomb Servant", "Crypt Shambler", "Ghoul", "Scarab", "Bonebeast" },
		-- -- minLevel = 1, 
		-- -- maxLevel = 70,
		-- -- kills = 150, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 150000 },
						-- -- { type = "item", item_id = 37606, count = 15 },
						-- -- { type = "item", item_id = 2160, count = 15 },
					  -- -- }
	   -- -- },
-- -- [4] = { name = "Cyclops",
        -- -- monsterList = { "Cyclops", "Cyclops Drone", "Cyclops Smith"},
		-- -- minLevel = 1, 
		-- -- maxLevel = 70,
		-- -- kills = 150, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 150000 },
						-- -- { type = "item", item_id = 37606, count = 15 },
						-- -- { type = "item", item_id = 2160, count = 15 },
					  -- -- }
	   -- -- },
-- -- [5] = { name = "Leaf Golem",
        -- -- monsterList = { "Leaf Golem", "Emerald Damselfly", "Insect Swarm", "Salamander", "Marsh Stalker", "Wilting Leaf Golem" },
		-- -- minLevel = 1, 
		-- -- maxLevel = 70,
		-- -- kills = 100, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 80000 },
						-- -- { type = "item", item_id = 37606, count = 10 },
						-- -- { type = "item", item_id = 2160, count = 11 },
					  -- -- }
	   -- -- },
-- -- [6] = { name = "Forest Fury",
        -- -- monsterList = { "Forest Fury", "Elder Forest Fury" },
		-- -- minLevel = 1, 
		-- -- maxLevel = 70,
		-- -- kills = 70, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 60000 },
						-- -- { type = "item", item_id = 37606, count = 9 },
						-- -- { type = "item", item_id = 2160, count = 9 },
					  -- -- }
	   -- -- },
-- -- [7] = { name = "Corym",
        -- -- monsterList = { "Corym Charlatan", "Corym Skirmisher", "Corym Vanguard Fury" },
		-- -- minLevel = 1, 
		-- -- maxLevel = 150,
		-- -- kills = 150, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 140000 },
						-- -- { type = "item", item_id = 37606, count = 15 },
						-- -- { type = "item", item_id = 2160, count = 20 },
					  -- -- }
	   -- -- },
-- -- [8] = { name = "Crystalcrusher",
        -- -- monsterList = { "Crystalcrusher", "Enraged Crystal Golem" },
		-- -- minLevel = 1, 
		-- -- maxLevel = 150,
		-- -- kills = 70, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 60000 },
						-- -- { type = "item", item_id = 37606, count = 9 },
						-- -- { type = "item", item_id = 2160, count = 9 },
					  -- -- }
	   -- -- },
-- -- [8] = { name = "Noble Lion",
        -- -- monsterList = { "Noble Lion", "Roaring Lion" },
		-- -- minLevel = 50, 
		-- -- maxLevel = 150,
		-- -- kills = 100, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 200000 },
						-- -- { type = "item", item_id = 37606, count = 20 },
						-- -- { type = "item", item_id = 2160, count = 20 },
					  -- -- }
	   -- -- },
-- -- [10] = { name = "Dragon",
        -- -- monsterList = { "Dragon", "Dragon Hatchling" },
		-- -- minLevel = 50, 
		-- -- maxLevel = 150,
		-- -- kills = 100, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 200000 },
						-- -- { type = "item", item_id = 37606, count = 20 },
						-- -- { type = "item", item_id = 2160, count = 20 },
					  -- -- }
	   -- -- },
-- -- [10] = { name = "Giant Spider",
        -- -- monsterList = { "Giant Spider" },
		-- -- minLevel = 50, 
		-- -- maxLevel = 150,
		-- -- kills = 100, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 200000 },
						-- -- { type = "item", item_id = 37606, count = 20 },
						-- -- { type = "item", item_id = 2160, count = 20 },
					  -- -- }
	   -- -- },
-- -- [11] = { name = "Putrid Mummy",
        -- -- monsterList = { "Putrid Mummy" },
		-- -- minLevel = 50, 
		-- -- maxLevel = 150,
		-- -- kills = 100, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 200000 },
						-- -- { type = "item", item_id = 37606, count = 20 },
						-- -- { type = "item", item_id = 2160, count = 20 },
					  -- -- }
	   -- -- },
-- -- [12] = { name = "Orc Cultist",
        -- -- monsterList = { "Orc Cultist", "Orc Cult Priest", "Orc Cult Inquisitor", "Orc Cult Minion", "Orc Cult Fanatic" },
		-- -- minLevel = 50, 
		-- -- maxLevel = 150,
		-- -- kills = 150, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 250000 },
						-- -- { type = "item", item_id = 37606, count = 25 },
						-- -- { type = "item", item_id = 2160, count = 25 },
					  -- -- }
	   -- -- },
-- -- [12] = { name = "Hero",
        -- -- monsterList = { "Renegade Knight","Hero", "Vile Grandmaster", "Vicious Squire", "Midnight Warrior" },
		-- -- minLevel = 80, 
		-- -- maxLevel = 200,
		-- -- kills = 300, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 500000 },
						-- -- { type = "item", item_id = 37606, count = 30 },
						-- -- { type = "item", item_id = 2160, count = 30 },
					  -- -- }
	   -- -- },
-- -- [13] = { name = "Sea Serpent",
        -- -- monsterList = { "Sea Serpent", "Young Sea Serpent", "Seacrest Serpent" },
		-- -- minLevel = 80, 
		-- -- maxLevel = 200,
		-- -- kills = 200, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 400000 },
						-- -- { type = "item", item_id = 37606, count = 30 },
						-- -- { type = "item", item_id = 2160, count = 30 },
					  -- -- }
	   -- -- },
 -- -- [14] = { name = "Dragon Lord",
        -- -- monsterList = { "Dragon Lord", "Dragon Lord Hatchling" },
		-- -- minLevel = 80, 
		-- -- maxLevel = 200,
		-- -- kills = 200, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 400000 },
						-- -- { type = "item", item_id = 37606, count = 30 },
						-- -- { type = "item", item_id = 2160, count = 30 },
					  -- -- }
	   -- -- },
-- -- [15] = { name = "Hydra",
        -- -- monsterList = { "Dragon Lord", "Dragon Lord Hatchling" },
		-- -- minLevel = 80, 
		-- -- maxLevel = 200,
		-- -- kills = 200, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 400000 },
						-- -- { type = "item", item_id = 37606, count = 30 },
						-- -- { type = "item", item_id = 2160, count = 30 },
					  -- -- }
	   -- -- },
-- -- [16] = { name = "Glooth Bandit",
        -- -- monsterList = { "Glooth Bandit", "Glooth Brigand" },
		-- -- minLevel = 80, 
		-- -- maxLevel = 200,
		-- -- kills = 300, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 500000 },
						-- -- { type = "item", item_id = 37606, count = 30 },
						-- -- { type = "item", item_id = 2160, count = 30 },
					  -- -- }
	   -- -- },
-- -- [17] = { name = "Yielothax",
        -- -- monsterList = { "Yielothax" },
		-- -- minLevel = 80, 
		-- -- maxLevel = 200,
		-- -- kills = 300, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 500000 },
						-- -- { type = "item", item_id = 37606, count = 30 },
						-- -- { type = "item", item_id = 2160, count = 30 },
					  -- -- }
	   -- -- },
-- -- [18] = { name = "Armadile",
        -- -- monsterList = { "Armadile", "Stone Devourer" },
		-- -- minLevel = 100, 
		-- -- maxLevel = 250,
		-- -- kills = 400, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 800000 },
						-- -- { type = "item", item_id = 37606, count = 60 },
						-- -- { type = "item", item_id = 2160, count = 60 },
					  -- -- }
	   -- -- },
-- -- [19] = { name = "Medusa",
        -- -- monsterList = { "Medusa", "Serpent Spawn" },
		-- -- minLevel = 100, 
		-- -- maxLevel = 250,
		-- -- kills = 400, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 800000 },
						-- -- { type = "item", item_id = 37606, count = 50 },
						-- -- { type = "item", item_id = 2160, count = 60 },
					  -- -- }
	   -- -- },
-- -- [20] = { name = "Lizard Chosen",
        -- -- monsterList = { "Lizard Chosen" },
		-- -- minLevel = 100, 
		-- -- maxLevel = 250,
		-- -- kills = 350, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 600000 },
						-- -- { type = "item", item_id = 37606, count = 30 },
						-- -- { type = "item", item_id = 2160, count = 35 },
					  -- -- }
	   -- -- },
-- -- [21] = { name = "Spectre",
        -- -- monsterList = { "Gazer Spectre", "Ripper Spectre", "Burster Spectre" },
		-- -- minLevel = 100, 
		-- -- maxLevel = 2000,
		-- -- kills = 800, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 3000000 },
						-- -- { type = "item", item_id = 37606, count = 100 },
						-- -- { type = "item", item_id = 2160, count = 120 },
					  -- -- }
	   -- -- },
-- -- [22] = { name = "Tunnel Tyrant",
        -- -- monsterList = { "Tunnel Tyrant" },
		-- -- minLevel = 100, 
		-- -- maxLevel = 250,
		-- -- kills = 400, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 8000000 },
						-- -- { type = "item", item_id = 37606, count = 50 },
						-- -- { type = "item", item_id = 2160, count = 60 },
					  -- -- }
	   -- -- },
-- -- [23] = { name = "Arachnophobica",
        -- -- monsterList = { "Arachnophobica" },
		-- -- minLevel = 200, 
		-- -- maxLevel = 9999,
		-- -- kills = 800, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 30000000 },
						-- -- { type = "item", item_id = 37606, count = 100 },
						-- -- { type = "item", item_id = 2160, count = 120 },
					  -- -- }
	   -- -- },
-- -- [24] = { name = "Arachnophobica",
        -- -- monsterList = { "Arachnophobica" },
		-- -- minLevel = 200, 
		-- -- maxLevel = 9999,
		-- -- kills = 800, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 30000000 },
						-- -- { type = "item", item_id = 37606, count = 100 },
						-- -- { type = "item", item_id = 2160, count = 120 },
					  -- -- }
	   -- -- },
-- -- [25] = { name = "Dark Torturer",
        -- -- monsterList = { "Dark Torturer" },
		-- -- minLevel = 200, 
		-- -- maxLevel = 9999,
		-- -- kills = 1000, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 35000000 },
						-- -- { type = "item", item_id = 37606, count = 100 },
						-- -- { type = "item", item_id = 2160, count = 120 },
					  -- -- }
	   -- -- },
-- -- [26] = { name = "Flimsy",
        -- -- monsterList = { "Flimsy Lost Soul", "Mean Lost Soul", "Freakish Lost", "Soul Torturer" },
		-- -- minLevel = 200, 
		-- -- maxLevel = 9999,
		-- -- kills = 1000, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 50000000 },
						-- -- { type = "item", item_id = 37606, count = 150 },
						-- -- { type = "item", item_id = 2160, count = 250 },
					  -- -- }
	   -- -- },
-- -- [27] = { name = "Grim Reaper",
        -- -- monsterList = { "Grim Reaper" },
		-- -- minLevel = 200, 
		-- -- maxLevel = 9999,
		-- -- kills = 1000, 
		-- -- ["Rewards"] = { 
		                -- -- { type = "experience", value = 35000000 },
						-- -- { type = "item", item_id = 37606, count = 100 },
						-- -- { type = "item", item_id = 2160, count = 120 },
					  -- -- }
	   -- -- },


-- }




-- T_STORAGES = 
-- {
-- checkTask = 34000,
-- killTask = 1800000,
-- countTask = 1900000,
-- bossTask = 2000000,
-- dificult = 2100000,
-- index = 2200000,
-- }


